# Generated by Django 4.2.1 on 2023-05-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environmentmodel",
            name="Environment",
            field=models.CharField(max_length=150, verbose_name="text"),
        ),
    ]
