# Generated by Django 4.2.1 on 2023-05-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formapp", "0002_alter_environmentmodel_environment"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreateData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=150, null=True)),
                ("state", models.CharField(blank=True, max_length=150, null=True)),
                ("location", models.CharField(blank=True, max_length=150, null=True)),
                ("environment", models.CharField(max_length=150, verbose_name="text")),
            ],
        ),
    ]
